# Generated by Django 4.0.1 on 2022-04-19 14:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='is_eamil',
            field=models.IntegerField(blank=True, null=True, verbose_name='답변 수신을 이메일로 받겠습니다.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='is_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='답변 수신을 문자메시지로 받겠습니다.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='작성자 전화번호'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
