# Generated by Django 4.0.1 on 2022-04-20 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_alter_inquiry_content_alter_inquiry_is_eamil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='updated_by_id',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='Inquiry/%Y%m%d', verbose_name='이미지 파일 업로드'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_by_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='질문 작성자'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='is_eamil',
            field=models.BooleanField(blank=True, null=True, verbose_name='답변 수신을 이메일로 받겠습니다.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='is_phone',
            field=models.BooleanField(blank=True, null=True, verbose_name='답변 수신을 문자메시지로 받겠습니다.'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(verbose_name='내용')),
                ('inquiry_id', models.ForeignKey(db_column='inquiry_id', on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('updated_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='답변 작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
